version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend/my-zerosupper-frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gradle
    directory: /backend/my-zerosupper-backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
